In [1]:
import pandas as pd
import numpy as np

# Load dataset (replace with your actual file path)
df = pd.read_csv("antiviral_drug_discovery.csv")

# Check first few rows
df.head()

SMILES    IC50     EC50  \
0  c1nc2ccc(N)c(cc1)c(c3c(c4ccc(c5ccc4OC)c5)ccc(O...  16.106   37.901   
1  C1=CC(CNC2=C1C3=CC=C(C=C3)C4=CC(C=C(C=C4)C(C)=...   0.000  149.890   
2  CCC(CC(=O)N(C(=O)NC(=O)C(=C(C(=O)N(C(=O)N(C(=O...  12.350   11.870   
3  CCOC1=CC(=C1)C(=O)C1=C(C=O)C(C(=O)C=C1C(=O)C1)...   3.460    1.060   
4                       CC(O)=C1C(O)N(C(O)=O)C(=O)N1  28.540    1.290   

        Ki       Kd PDB_ID  Binding_Affinity  Absorption  Distribution  \
0   21.631   51.336   4G6D            -6.817      0.9922         3.342   
1  128.000  124.990   3P2Z            -7.200      0.4130         4.040   
2   14.970    2.820   6J5K            -7.516     58.8800         0.957   
3    3.380    0.330   2E6O            -7.275      0.2240         1.870   
4    7.920    4.320   1j1c            -7.878      0.9990         0.980   

   Metabolism  Excretion  Toxicity  
0      0.1809     0.0101     0.623  
1      0.0000     0.1960     1.550  
2      2.4640     0.8850     1.371  
3      0.0250     0.0070     0.956  
4      0.9480     0.9990     0.018

In [2]:
print(df.isnull().sum())  # Count missing values per column

# Fill missing numerical values with the mean
df.fillna(df.select_dtypes(include=['number']).mean(), inplace=True)

# Fill missing categorical values with mode
df.fillna(df.mode().iloc[0], inplace=True)

SMILES              0
IC50                0
EC50                0
Ki                  0
Kd                  0
PDB_ID              0
Binding_Affinity    0
Absorption          0
Distribution        0
Metabolism          0
Excretion           0
Toxicity            0
dtype: int64


In [3]:
df.drop_duplicates(inplace=True)

In [4]:
df.columns = df.columns.str.lower().str.replace(" ", "_")

In [5]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[['ic50', 'ec50', 'ki', 'kd']] = scaler.fit_transform(df[['ic50', 'ec50', 'ki', 'kd']])

In [6]:
df.to_csv("cleaned_antiviral_drug_discovery.csv", index=False)

In [7]:
print(df.isnull().sum())  # Count missing values per column

# Fill missing numerical values with the mean
df.fillna(df.select_dtypes(include=['number']).mean(), inplace=True)

# Fill missing categorical values with mode
df.fillna(df.mode().iloc[0], inplace=True)

smiles              0
ic50                0
ec50                0
ki                  0
kd                  0
pdb_id              0
binding_affinity    0
absorption          0
distribution        0
metabolism          0
excretion           0
toxicity            0
dtype: int64


In [8]:
pip install --upgrade rdkit

In [9]:
df=pd.read_csv('cleaned_valid_smiles.csv')
df

smiles      ic50      ec50  \
0   CCOC1=CC(=C1)C(=O)C1=C(C=O)C(C(=O)C=C1C(=O)C1)...  0.017300  0.005988   
1                        CC(O)=C1C(O)N(C(O)=O)C(=O)N1  0.142700  0.007422   
2                                         C1=CC=CC=C1  0.055397  0.095251   
3                                   C1=CC=CC=C1C(=O)O  0.006770  0.016822   
4                           CC(C)C(C)C1=CC=CC(=O)C=C1  0.334500  0.124119   
5                             CC(=O)C(=O)[N+]([O-])=O  0.175000  0.074222   
6         c1cc(ccc1)OCC(C(=O)Nc2ccccc2)C1=CC=C(O)C=C1  0.373550  0.101291   
7                                 CC(=O)NC1CN(CCCN1)C  0.142300  1.000000   
8   CC(O)CC(=O)[C@@H](NC1=CC2=CC=CC=C2SC(=O)C(=O)C...  0.124800  0.014907   
9                    CN1CCC(=C(OC(=C1C)C)C)C(=C1)CCC1  0.009600  0.010229   
10                       CC(=O)C(=O)C(C=O)C1=CC=CC=C1  0.232950  0.066051   
11                                     C=CC1=CC=CC=C1  0.109500  0.014969   
12             CCC1=C(C2=CC=C(C(C(=O)NCC2=CC=C1)O)C)C  0.013000  0.043660   
13                                  [H]C([H])([H])[H]  0.750000  0.934947   

          ki        kd pdb_id  binding_affinity  absorption  distribution  \
0   0.012637  0.000595   2E6O         -7.275000    0.224000        1.8700   
1   0.029612  0.012643   1j1c         -7.878000    0.999000        0.9800   
2   0.009069  0.001875   3L2M         -6.603080    0.613700        0.9393   
3   0.002632  0.003491   1F0X         -9.613000    0.950000        1.5830   
4   0.055709  0.126725   5JBK         -7.724000    0.885600        1.3550   
5   0.041128  0.109105   2FU4         -7.673556    0.748200        2.8100   
6   0.417408  0.072462   2L2S         -7.821000    0.127000       11.2500   
7   0.037351  0.035924   6k45        -10.900000    0.990000      116.1000   
8   0.005234  0.002618   6H0Q         -6.707260    0.153774        1.9700   
9   0.066477  0.033720   6LVK         -8.110000    0.640000        6.1300   
10  0.046512  0.032150   4IDG          6.349000    0.660020        0.6630   
11  0.007478  0.025265   2JQ3         -8.000000    0.081000        0.7220   
12  0.031780  0.012583   4FQE         -7.100000    0.981000        1.2400   
13  0.416137  1.000000   4b89         -5.700000    0.999000        1.8900   

    metabolism  excretion  toxicity  
0     0.025000   0.007000  0.956000  
1     0.948000   0.999000  0.018000  
2     0.901200   0.954400  1.497200  
3     1.000000   0.324000  1.140000  
4     1.000000   1.000000  1.000000  
5     0.453400   0.189400 -2.460691  
6     0.145000   1.249000  0.460000  
7     0.770000   0.410000  0.700000  
8     0.014323   0.156042  2.428000  
9     0.105000   0.374000  2.010000  
10    0.576090   0.279350  0.445000  
11    0.030000   0.010000  0.020000  
12    1.000000   0.139000  0.834000  
13    0.000000   0.952000  0.240000

In [10]:
from rdkit import Chem
from rdkit.Chem import AllChem

def smiles_to_fingerprint(smiles, radius=2, n_bits=2048):
    mol = Chem.MolFromSmiles(smiles)
    if mol:
        fp = AllChem.GetMorganFingerprintAsBitVect(mol, radius, nBits=n_bits)
        return np.array(fp)
    return None

In [11]:
# Example
smiles = "CCO"
fingerprint = smiles_to_fingerprint(smiles)
print(fingerprint.shape)  # (2048,)

(2048,)


[09:50:15] DEPRECATION WARNING: please use MorganGenerator


In [12]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LeakyReLU, BatchNormalization
df["fingerprint"] = df["smiles"].apply(lambda x: smiles_to_fingerprint(x))

# Remove empty fingerprints
df = df.dropna(subset=["fingerprint"])
X_train = np.array(df["fingerprint"].tolist())  # Convert to NumPy array

[09:50:54] DEPRECATION WARNING: please use MorganGenerator
[09:50:54] DEPRECATION WARNING: please use MorganGenerator
[09:50:54] DEPRECATION WARNING: please use MorganGenerator
[09:50:54] DEPRECATION WARNING: please use MorganGenerator
[09:50:54] DEPRECATION WARNING: please use MorganGenerator
[09:50:54] DEPRECATION WARNING: please use MorganGenerator
[09:50:54] DEPRECATION WARNING: please use MorganGenerator
[09:50:54] DEPRECATION WARNING: please use MorganGenerator
[09:50:54] DEPRECATION WARNING: please use MorganGenerator
[09:50:54] DEPRECATION WARNING: please use MorganGenerator
[09:50:54] DEPRECATION WARNING: please use MorganGenerator
[09:50:54] DEPRECATION WARNING: please use MorganGenerator
[09:50:54] DEPRECATION WARNING: please use MorganGenerator
[09:50:54] DEPRECATION WARNING: please use MorganGenerator


In [13]:
#Build the Generator
def build_generator(input_dim=100, output_dim=2048):
    model = Sequential([
        Dense(256, input_dim=input_dim),
        LeakyReLU(alpha=0.2),
        BatchNormalization(momentum=0.8),
        Dense(512),
        LeakyReLU(alpha=0.2),
        BatchNormalization(momentum=0.8),
        Dense(1024),
        LeakyReLU(alpha=0.2),
        BatchNormalization(momentum=0.8),
        Dense(output_dim, activation="sigmoid")  # Output drug fingerprints
    ])
    return model


In [14]:
#Build the Discriminator
def build_discriminator(input_dim=2048):
    model = Sequential([
        Dense(1024, input_dim=input_dim),
        LeakyReLU(alpha=0.2),
        Dense(512),
        LeakyReLU(alpha=0.2),
        Dense(256),
        LeakyReLU(alpha=0.2),
        Dense(1, activation="sigmoid")  # Binary classification (Real or Fake)
    ])
    return model

In [15]:
#Compile the GAN
# Initialize models
generator = build_generator()
discriminator = build_discriminator()

# Compile Discriminator
discriminator.compile(loss="binary_crossentropy", optimizer=tf.keras.optimizers.Adam(0.0002, 0.5), metrics=["accuracy"])

# Freeze Discriminator for GAN training
discriminator.trainable = False

# Build GAN
gan_input = tf.keras.Input(shape=(100,))
generated_drugs = generator(gan_input)
validity = discriminator(generated_drugs)

gan = tf.keras.Model(gan_input, validity)
gan.compile(loss="binary_crossentropy", optimizer=tf.keras.optimizers.Adam(0.0002, 0.5))

C:\Users\Dell\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Dell\anaconda3\Lib\site-packages\keras\src\layers\activations\leaky_relu.py:41: UserWarning: Argument `alpha` is deprecated. Use `negative_slope` instead.
  warnings.warn(


In [16]:
import matplotlib.pyplot as plt

# Training Parameters
epochs = 500
batch_size = 32
noise_dim = 100

# Labels for real and fake drugs
real = np.ones((batch_size, 1))
fake = np.zeros((batch_size, 1))

# Training Loop
for epoch in range(epochs):
    # Train Discriminator
    idx = np.random.randint(0, X_train.shape[0], batch_size)
    real_drugs = X_train[idx]
    noise = np.random.normal(0, 1, (batch_size, noise_dim))
    generated_drugs = generator.predict(noise)
    
    d_loss_real = discriminator.train_on_batch(real_drugs, real)
    d_loss_fake = discriminator.train_on_batch(generated_drugs, fake)
    d_loss = 0.5 * np.add(d_loss_real, d_loss_fake)

    # Train Generator
    noise = np.random.normal(0, 1, (batch_size, noise_dim))
    g_loss = gan.train_on_batch(noise, real)

    # Print Progress
    if epoch % 100 == 0:
        print(f"Epoch {epoch}: D Loss={d_loss[0]}, G Loss={g_loss}")



1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step


C:\Users\Dell\anaconda3\Lib\site-packages\keras\src\backend\tensorflow\trainer.py:82: UserWarning: The model does not have any trainable weights.
  warnings.warn("The model does not have any trainable weights.")


Epoch 0: D Loss=0.715165913105011, G Loss=0.6763705015182495
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 185ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 285ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 185ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 211ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 216ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step
1/1

In [17]:
# Save the trained Generator
generator.save("gan_generator.h5")

In [18]:
# generated_molecular_fingerprints
generator = tf.keras.models.load_model("gan_generator.h5")
noise = np.random.normal(0, 1, (5, 100))
generated_fingerprints = generator.predict(noise)
print(generated_fingerprints) #These are the generated molecular fingerprints produced by your GAN model.

# Each row in this (5, 2048) NumPy array represents a 2048-bit fingerprint of a newly generated drug-like molecule. 

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 617ms/step
[[4.5994270e-01 8.2397902e-01 2.0875759e-01 ... 1.5297905e-01
  9.7624075e-01 9.1541272e-01]
 [9.2375100e-01 5.4438019e-01 8.7494415e-01 ... 9.5357460e-01
  7.1323775e-03 6.8614088e-02]
 [9.7489125e-01 5.9376085e-01 9.1186017e-01 ... 9.5850009e-01
  3.2667493e-04 2.4166657e-02]
 [9.2497981e-01 9.8754418e-01 8.8219938e-05 ... 6.7192632e-05
  9.9985993e-01 9.9684429e-01]
 [1.6240633e-01 6.5367162e-01 5.3384914e-03 ... 3.1099957e-03
  9.9926895e-01 9.9096930e-01]]


In [19]:
# Binary Fingerprints
binary_fingerprints = (generated_fingerprints > 0.5).astype(int)

# Print the binary fingerprints
print(binary_fingerprints)

[[0 1 0 ... 0 1 1]
 [1 1 1 ... 1 0 0]
 [1 1 1 ... 1 0 0]
 [1 1 0 ... 0 1 1]
 [0 1 0 ... 0 1 1]]


In [20]:
# Convert fingerprints back to SMILES (using RDKit)
from rdkit import DataStructs

def fingerprint_to_smiles(fp):
    # Placeholder function: You will need a trained model to convert fingerprints back to SMILES.
    return "Generated_SMILES_String"

generated_smiles = [fingerprint_to_smiles(fp) for fp in generated_fingerprints]
print(generated_smiles)

['Generated_SMILES_String', 'Generated_SMILES_String', 'Generated_SMILES_String', 'Generated_SMILES_String', 'Generated_SMILES_String']


In [21]:
from rdkit import Chem, DataStructs
from rdkit.Chem import AllChem
import numpy as np
import pandas as pd

# Load your reference dataset (SMILES and their fingerprints)
ref_df = pd.read_csv("C:/Users/Dell/Downloads/GDG Solution challenge/Fingerprints_with_SMILES.csv")  # Contains 'smiles' column
ref_fingerprints = [
    AllChem.GetMorganFingerprintAsBitVect(Chem.MolFromSmiles(x), 2, nBits=2048)
    for x in ref_df["SMILES"]
]

# Function to find the closest match
def fingerprint_to_smiles(generated_fp, ref_fingerprints, ref_smiles):
    max_similarity = 0
    best_match = None
    
    for ref_fp, smiles in zip(ref_fingerprints, ref_smiles):
        sim = DataStructs.FingerprintSimilarity(generated_fp, ref_fp)
        if sim > max_similarity:
            max_similarity = sim
            best_match = smiles
            
    return best_match, max_similarity

# Convert your generated fingerprints to RDKit format
generated_fps = [
    DataStructs.ExplicitBitVect(len(fp)) for fp in generated_fingerprints
]

# Set the bits manually
for i, fp in enumerate(generated_fingerprints):
    for bit_idx in np.where(fp)[0]:  # Get indices of 1s
        generated_fps[i].SetBit(int(bit_idx))  # Ensure it's a Python int
# Find closest molecules
for fp in generated_fps:
    smiles, similarity = fingerprint_to_smiles(fp, ref_fingerprints, ref_df["SMILES"])
    print(f"Generated Molecule: {smiles}, Similarity: {similarity}")


[09:55:33] DEPRECATION WARNING: please use MorganGenerator
[09:55:33] DEPRECATION WARNING: please use MorganGenerator
[09:55:33] DEPRECATION WARNING: please use MorganGenerator
[09:55:33] DEPRECATION WARNING: please use MorganGenerator
[09:55:33] DEPRECATION WARNING: please use MorganGenerator
[09:55:33] DEPRECATION WARNING: please use MorganGenerator
[09:55:33] DEPRECATION WARNING: please use MorganGenerator
[09:55:33] DEPRECATION WARNING: please use MorganGenerator
[09:55:33] DEPRECATION WARNING: please use MorganGenerator
[09:55:33] DEPRECATION WARNING: please use MorganGenerator
[09:55:33] DEPRECATION WARNING: please use MorganGenerator
[09:55:33] DEPRECATION WARNING: please use MorganGenerator
[09:55:33] DEPRECATION WARNING: please use MorganGenerator
[09:55:33] DEPRECATION WARNING: please use MorganGenerator
[09:55:33] DEPRECATION WARNING: please use MorganGenerator
[09:55:33] DEPRECATION WARNING: please use MorganGenerator
[09:55:33] DEPRECATION WARNING: please use MorganGenerat

Generated Molecule: CCC1=CC2Cc3nc4cc(Cl)ccc4c(NCCn4cc(CCCCCCN5CCc6cc(OC)c(OC)cc6C5c5cccc([N+](=O)[O-])c5)nn4)c3C(C1)C2, Similarity: 0.05126953125
Generated Molecule: CCC1=CC2Cc3nc4cc(Cl)ccc4c(NCCn4cc(CCCCCCN5CCc6cc(OC)c(OC)cc6C5c5cccc([N+](=O)[O-])c5)nn4)c3C(C1)C2, Similarity: 0.05126953125
Generated Molecule: CCC1=CC2Cc3nc4cc(Cl)ccc4c(NCCn4cc(CCCCCCN5CCc6cc(OC)c(OC)cc6C5c5cccc([N+](=O)[O-])c5)nn4)c3C(C1)C2, Similarity: 0.05126953125
Generated Molecule: CCC1=CC2Cc3nc4cc(Cl)ccc4c(NCCn4cc(CCCCCCN5CCc6cc(OC)c(OC)cc6C5c5cccc([N+](=O)[O-])c5)nn4)c3C(C1)C2, Similarity: 0.05126953125
Generated Molecule: CCC1=CC2Cc3nc4cc(Cl)ccc4c(NCCn4cc(CCCCCCN5CCc6cc(OC)c(OC)cc6C5c5cccc([N+](=O)[O-])c5)nn4)c3C(C1)C2, Similarity: 0.05126953125
